### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by icepuma** [softprops/goji#44]
Could you please release goji. The bumped versions should fix a problem that I have with the openssl crate.

Best regards
Stefan

**Comment by matthewarmand** [comment]
Experiencing this same issue, would love to see a new release cut for this @softprops. `goji 0.2.4` depends on `reqwest 0.7`, which does not support systems with `openssl 1.1.1`.

Because it involves a more recent `reqwest` version bump as well as some other fixes, might be good to cut a release after merging in #48
